{% set name = "meegkit" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meegkit-{{ version }}.tar.gz
  sha256: 5032dfaf10725f22c02bea5f4ec9ef150b0f11e9297eac8c5d56cac87da5d282

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.0.0
    - wheel
    - pybind11 >=2.10.3,<2.11.dev0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scipy
    - matplotlib-base
    - scikit-learn
    - pandas
    - joblib
    - tqdm
    - statsmodels
    - pyriemann >=0.2.7

test:
  imports:
    - meegkit
  commands:
    - pip check
    - python -c "import meegkit; assert meegkit.__version__ == '{{ version }}'"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://nbara.github.io/python-meegkit
  summary: M/EEG denoising in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
